Update to read daemon list from package.json
LiskHQ/dev-cli pull request #3
Opened 2020-12-07 15:56 UTC by shuse2

Update to read the package json daemons list to change the execution command.

2020-12-07 16:05 UTC, fchavant requested changes

2020-12-07 16:05 UTC, fchavant commented on src/tarballs/bin.ts
> +    const daemons = config.pjson.lisk?.daemons?.join('|') ?? '';
Do we assume the "daemons" commands contain no `|` or ` `?

2020-12-07 16:05 UTC, fchavant commented on src/tarballs/bin.ts
> +  case $1 in
We should check if `${daemons} == ''` and if so skip the this block and unconditionnaly run `"$NODE" "$DIR/run" "$@"` instead.

2020-12-07 16:10 UTC, shuse2 commented on src/tarballs/bin.ts
> +    const daemons = config.pjson.lisk?.daemons?.join('|') ?? '';
`daemons` is a string array, which should not contain any thing other than command itself

2020-12-07 16:47 UTC, shuse2 commented on src/tarballs/bin.ts
> +  case $1 in
Updated to use different logic in case daemons is empty

2020-12-07 16:51 UTC, fchavant approved these changes

2020-12-08 08:33 UTC, Nazgolze approved these changes

2020-12-08 09:07 UTC, merged